---
- name: turing
  hosts: all
  remote_user: root
  vars:
    # So we don't have to install python2.7
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - storage
    - update-system
    - security
    - acme
    - www
    - ssl
    - static-sites
    - xmpp
