---
- name: Update all packages to the latest version
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
  async: 540
  poll: 10

- name: Check if a reboot is required
  register: reboot_required
  stat:
    path: /var/run/reboot-required
    get_md5: no

- name: Server is about to reboot
  pause:
    prompt: 'Please confirm pending reboot! Press return to continue. Press Ctrl+c and then "a" to abort'
  when: reboot_required.stat.exists == true and env == 'production'

- name: Reboot the server
  shell: sleep 2 && /sbin/shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_required.stat.exists == true

- name: Wait for server to start again
  pause:
    seconds: 60
  when: reboot_required.stat.exists == true

- name: Check for correctly started server
  shell: uptime
  when: reboot_required.stat.exists == true

- name: Enable automatic updates
  apt:
    package: unattended-upgrades
    state: installed
    force: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Configure automatic updates
  copy:
    src: files/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
