language: generic
sudo: required
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    secure: rjBnRhyZZOynCCekdismbp8hgePHprajrwHIhdpjatHtbt4XGBrqEhiRezTYf4K+FllFXyXG0gb47fryMGrn8hU0gDJ523Af/LnydXAAt4UShwA1xxhNjOx1dAYjjA19dxmVVJDYKPtV3PHaIsgFGQcVif4bLid2qaByOfGwEnWj0+F+ZUnfCDX37oSILc30mdJI7e1wGGq1UQo5Dus3zL/CISZ1TCDEm8MpDlicEA/Ui/s/89rqmGd/Tv8UjGt6jePB1K8y+L5vn6bZgjK1l4x2ZbLYGNNdL7ZhUpUXfzSHy04ITMEx3EtSQUyeA7fuV4vAFb1MiZIX+PSDrK5f2SixCozEA3G//+jZA9x7tZuFx2NGCMZx/dV6KdpuXp8n6idXDmu1IjTCnZ7fMtogd1KzCQLPhP44lkidMyrAlCbYltt31Otx76iahwI/99td+m1yfLRrRqKsJhTmSBBMetRsO/k6is9tdat1FRXLnY6rWlrtzR5kDUcvospo4tmgrBTUJLVhFLG1FP60ftcqsDbHQVtCSVqXTkGAQ2JYGA58FBn+iy5RS3wRwBGGb007uV9TNyMP31PjBm6zZhQ4UsOEgWuCxMwnYaeQpy3c195O2uh88FNvz29kjpdxYSIl8vJV+ksxleF9xZYBjZKUeqHLwrHWXHb1gSJtS4leWQs=
before_install:
  - ./go prepare-ci
  - ./go purge-do
script:
  - ./go test
after_script:
  - ./go clean
