---
- set_fact:
    mail:
      domain: example.org
      hostname: mail.example.org
      uid: 2222
      gid: 2222
      user: vmail
      group: vmail
      maildir: "{{ data_dir }}/mail/vmail"
      domains:
        - example.org
        - foo.com
        - bar.com

# - name: Set Postfix option hostname
#   debconf:
#     name: postfix
#     question: "postfix/mailname"
#     value: "{{ mail.fqdn }}"
#     vtype: "string"
# 
# - name: Set Postfix option type as internet site
#   debconf:
#     name: postfix
#     question: "postfix/main_mailer_type"
#     value: "'Internet Site'"
#     vtype: "string"

- group:
    name: "{{ mail.group }}"
    gid: "{{ mail.gid }}"
    state: present

- user:
    name: "{{ mail.user }}"
    group: "{{ mail.group }}"
    uid: "{{ mail.uid }}"
    home: "{{ mail.maildir }}"
    shell: /usr/bin/nologin
    createhome: no

- file:
    path: "{{ mail.maildir }}"
    owner: "{{ mail.user }}"
    group: "{{ mail.group }}"
    state: directory
    mode: "u=rwx,g=rx,o-rwx"

- file:
    path: "{{ mail.maildir }}/{{ item }}"
    owner: "{{ mail.user }}"
    group: "{{ mail.group }}"
    state: directory
    mode: "u=rwx,g=rx,o-rwx"
  with_items: "{{ mail.domains }}"

- name: Install Postfix
  apt:
    package: "{{ item }}"
    state: installed
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - postfix
    - mailutils

- name: Allow mail traffic
  ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
  with_items:
    - { rule: 'allow', port: '25', proto: 'tcp' }
    - { rule: 'allow', port: '2525', proto: 'tcp' }

- name: Redirect from 2525 to 25 to circumvent firewalls
  iptables:
     table: nat
     chain: PREROUTING
     protocol: tcp
     match: tcp
     destination_port: 2525
     jump: REDIRECT
     to_ports: 25
     comment: Redirect mail traffic from 2525 to 25

- name: Configure main postfix
  template:
    src: templates/postfix-main.cf
    dest: /etc/postfix/main.cf
    mode: "u=r,g=r,o=r"
  notify:
    - restart postfix

- name: Configure virtual mailboxes
  template:
    src: templates/virtual_mailbox_maps
    dest: /etc/postfix/virtual_mailbox_maps
    mode: "u=r,g=r,o=r"
  notify:
    - restart postfix

- name: Ensure running postfix
  service:
    name: postfix
    state: started
    enabled: yes
