---
- blockinfile:
    path: /etc/network/interfaces
    block: |
      iface eth0 inet static
        address {{ item }}/32
        netmask 255.255.255.0
  with_items: "{{ ips }}"
  register: reload_network

- name: restart network
  shell: 'ifdown eth0 && ifup eth0'
  when: reload_network|changed
