---
- set_fact:
    acme:
      user: acme-webroot
      group: acme-webroot
      webroot: /var/lib/acme-webroot

- group:
    name: "{{ acme.group }}"
    state: present

- user:
    name: "{{ acme.user }}"
    group: "{{ acme.group }}"
    home: "{{ acme.webroot }}"
    shell: /usr/bin/nologin
    createhome: no

- file:
    path: "{{ acme.webroot }}"
    owner: "{{ acme.user }}"
    group: "{{ acme.group }}"
    state: directory
    mode: "u=rwx,g=rwx,o-rwx"

- include: create-test-challenge.yml
  when: "'test' in group_names"
