---
- set_fact:
    acme:
      user: acme-webroot
      group: acme-webroot
      webroot: /var/lib/acme-webroot

- group:
    name: "{{ acme.group }}"
    state: present

- user:
    name: "{{ acme.user }}"
    group: "{{ acme.group }}"
    home: "{{ acme.webroot }}"
    shell: /bin/false
    createhome: no

- file:
    path: "{{ item }}"
    owner: "{{ acme.user }}"
    group: "{{ acme.group }}"
    state: directory
    mode: "u=rwx,g=rwx,o-rwx"
  with_items:
    - "{{ acme.webroot }}"
    - "{{ acme.webroot }}/.well-known"
    - "{{ acme.webroot }}/.well-known/acme-challenge"

- include: create-test-challenge.yml
  when: "'test' in group_names"
