- name: Install git
  apt:
    package: git
    state: present
    update_cache: yes

- name: Create git user
  user:
    name: "git"
    home: "{{ data_dir }}/git"
    shell: /usr/bin/git-shell

- name: Allow git access for configured others
  authorized_key:
    user: "git"
    state: present
    key: '{{ item }}'
  with_items: "{{ git.pubkeys }}"
