---
- name: Create folders for test certificates
  file:
    path: "{{ ssl.certificates_dir }}/{{ item }}"
    owner: certbot
    group: certbot
    state: directory
    mode: "u=rwx,g=rx,o-rwx"
  with_items: "{{ domains }}"

- name: Generate test certificates
  shell: |
    domain="{{ item }}"
    path="{{ ssl.certificates_dir }}/$domain"

    openssl req -x509 -newkey rsa:2048 \
      -keyout "${path}/privkey.pem" \
      -out "${path}/fullchain.pem" \
      -nodes \
      -days 365 \
      -subj "/C=DE/L=Test/OU=Test/CN=${domain}"
  with_items: "{{ domains }}"
