---
- set_fact:
    ssl:
      certificates_dir: /etc/certificates

- apt_repository:
    repo: ppa:certbot/certbot
    state: present

- name: Install certbot
  apt:
    package: certbot
    state: present
    update_cache: yes

- group:
    name: certbot
    state: present

- user:
    name: certbot
    group: certbot
    home: /var/lib/letsencrypt
    shell: /usr/bin/nologin

- name: Allow certbot to access acme webroot
  user:
    name: certbot
    groups: "{{ acme.group }}"
    append: yes

- name: Allow certbot to access acme webroot
  user:
    name: nginx
    groups: "{{ acme.group }}"
    append: yes

- file:
    path: '{{ item }}'
    owner: certbot
    group: certbot
    state: directory
    mode: "u=rwx,g=rx,o-rwx"
  with_items:
    - "{{ ssl.certificates_dir }}"
    - /etc/letsencrypt
    - /etc/letsencrypt/live
    - /var/lib/letsencrypt
    - /var/log/letsencrypt

- name: Create folders for certificates
  file:
    path: "{{ ssl.certificates_dir }}/{{ item }}"
    owner: certbot
    group: certbot
    state: directory
    mode: "u=rwx,g=rx,o-rwx"
  with_items: "{{ domains }}"

- name: Generate certificates
  script: "scripts/obtain-or-renew-certificate.sh {{ acme.webroot }} {{ ssl.certificates_dir }} {{ owner.cert_mail }} {{ item }} {{ env }}"
  args:
    creates: "{{ ssl.certificates_dir }}/{{ item }}/privkey.pem"
  become: yes
  become_user: certbot
  with_items: "{{ domains }}"
