---
- apt_repository:
    repo: ppa:certbot/certbot
    state: present

- name: Install certbot
  apt:
    package: certbot
    state: present
    update_cache: yes

- group:
    name: certbot
    state: present

- user:
    name: certbot
    group: certbot
    home: /var/lib/letsencrypt
    shell: /usr/bin/nologin

- name: Allow certbot to access acme webroot
  user:
    name: nginx
    groups: "{{ acme.group }}"
    append: yes

- file:
    path: '{{ item }}'
    owner: certbot
    group: certbot
    state: directory
    mode: "u=rwx,g=rx,o-rwx"
  with_items:
    - /etc/letsencrypt
    - /var/lib/letsencrypt
    - /var/log/letsencrypt

- name: Configure certbot
  template:
    src: templates/letsencrypt.ini.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: nginx
    mode: "u=rx,g=rx,o-rwx"
