---
- group:
    name: "deploy-{{ site.name }}"
    state: present

# TODO: Restrict deploy user to rsync in ~/www
- name: Create deploy user
  user:
    name: "deploy-{{ site.name }}"
    group: "deploy-{{ site.name }}"
    home: "{{ static_sites_config.www_home }}/{{ site.name }}"
    shell: /bin/bash
    createhome: no
    password: "{{ lookup('password', '/dev/null length=64') | password_hash('sha512') }}"
    update_password: on_create

- name: Allow nginx to access deploy webroot
  user:
    name: nginx
    groups: "deploy-{{ site.name }}"
    append: yes

- file:
    path: "{{ item }}"
    owner: "deploy-{{ site.name }}"
    group: "deploy-{{ site.name }}"
    state: directory
    mode: "u=rwx,g=rx,o-rwx"
  with_items:
    - "{{ static_sites_config.www_home }}/{{ site.name }}"
    - "{{ static_sites_config.www_home }}/{{ site.name }}/www"

- name: Allow access for the server owner
  authorized_key:
    user: "deploy-{{ site.name }}"
    state: present
    key: '{{ item }}'
  with_items: "{{ owner.pubkeys }}"

- name: Add nginx configuration
  template:
    src: templates/nginx-vhost.conf.j2
    dest: "/etc/nginx/conf.d/{{ site.name }}.conf"
    owner: nginx
    mode: "u=rx,g=rx,o-rwx"
  notify:
    - restart nginx

- file:
    path: "/etc/nginx/htpasswd"
    owner: "nginx"
    group: "nginx"
    state: directory
    mode: "u=rx,g=rx,o-rwx"

- name: Add access restriction
  htpasswd:
    path:  "/etc/nginx/htpasswd/{{ site.name }}"
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    owner: nginx
    group: nginx
    mode: "u=rx,g=rx,o-rwx"
  when: site.restricted is defined
  items: "{{ site.restricted }}"
  notify:
    - restart nginx

- name: Add default landing page if not existing
  copy:
    src: files/index.html
    dest: "{{ static_sites_config.www_home }}/{{ site.name }}/www/index.html"
    force: no
    owner: "deploy-{{ site.name }}"
    group: "deploy-{{ site.name }}"
    mode: "u=rwx,g=rx,o-rwx"
