---
- group:
    name: "deploy-{{ site.name }}"
    state: present

# TODO: Restrict deploy user to rsync in ~/www
- name: Create deploy user
  user:
    name: "deploy-{{ site.name }}"
    group: "deploy-{{ site.name }}"
    home: "/var/www/deploy-{{ site.name }}"
    shell: /bin/bash
    createhome: no
    password: "{{ lookup('password', '/dev/null length=64') | password_hash('sha512') }}"
    update_password: on_create

- name: Allow nginx to access deploy webroot
  user:
    name: nginx
    groups: "deploy-{{ site.name }}"
    append: yes

- file:
    path: "{{ item }}"
    owner: "deploy-{{ site.name }}"
    group: "deploy-{{ site.name }}"
    state: directory
    mode: "u=rwx,g=rx,o-rwx"
  with_items:
    - "/var/www/deploy-{{ site.name }}"
    - "/var/www/deploy-{{ site.name }}/www"

- name: Allow access for the server owner
  authorized_key:
    user: "deploy-{{ site.name }}"
    state: present
    key: '{{ item }}'
  with_items: "{{ owner.pubkeys }}"

- name: Add nginx configuration
  template:
    src: templates/nginx-vhost.conf.j2
    dest: "/etc/nginx/conf.d/{{ site.name }}.conf"
    owner: nginx
    mode: "u=rx,g=rx,o-rwx"
  notify:
    - reload nginx
