---
- set_fact:
    static_sites_config:
      www_home: "{{ data_dir }}/static_sites"

- name: Ensure static site base dir
  file:
    path: "{{ static_sites_config.www_home }}"
    owner: "root"
    group: "root"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Enable static sites
  include: enable-static-website.yml site={{outer_item}}
  with_items: "{{ static_sites }}"
  loop_control:
    loop_var: outer_item
